In [9]:
import pandas as pd

In [12]:
df=pd.read_csv('imdb.csv')

In [13]:
df.head()

,Director,Film_Country,Film_Date,Film_Name,Film_Rate,Stars
0,Frank Darabont,USA,14 October 1994,The Shawshank Redemption,9.3,"Tim Robbins,Morgan Freeman,Bob Gunton"
1,Christopher Nolan,USA,18 July 2008,The Dark Knight,9.0,"Christian Bale,Heath Ledger,Aaron Eckhart"
2,Francis Ford Coppola,USA,18 December 1974,The Godfather: Part II,9.0,"Al Pacino,Robert De Niro,Robert Duvall"
3,Hayao Miyazaki,USA,19 December 1997,Princess Mononoke,8.4,"Yôji Matsuda,Yuriko Ishida,Yûko Tanaka"
4,Francis Ford Coppola,USA,24 March 1972,The Godfather,9.2,"Marlon Brando,Al Pacino,James Caan"

In [14]:
films=len(df)

In [15]:
films

328

In [16]:
new_df=df[['Film_Name','Film_Date','Film_Country','Film_Rate','Director','Stars']]
new_df

,Film_Name,Film_Date,Film_Country,Film_Rate,Director,Stars
0,The Shawshank Redemption,14 October 1994,USA,9.3,Frank Darabont,"Tim Robbins,Morgan Freeman,Bob Gunton"
1,The Dark Knight,18 July 2008,USA,9.0,Christopher Nolan,"Christian Bale,Heath Ledger,Aaron Eckhart"
2,The Godfather: Part II,18 December 1974,USA,9.0,Francis Ford Coppola,"Al Pacino,Robert De Niro,Robert Duvall"
3,Princess Mononoke,19 December 1997,USA,8.4,Hayao Miyazaki,"Yôji Matsuda,Yuriko Ishida,Yûko Tanaka"
4,The Godfather,24 March 1972,USA,9.2,Francis Ford Coppola,"Marlon Brando,Al Pacino,James Caan"
...,...,...,...,...,...,...
323,12 Angry Men,10 April 1957,USA,8.9,Sidney Lumet,"Henry Fonda,Lee J. Cobb,Martin Balsam"
324,"The Good, the Bad and the Ugly",29 December 1967,USA,8.8,Sergio Leone,"Clint Eastwood,Eli Wallach,Lee Van Cleef"
325,Pulp Fiction,14 October 1994,USA,8.9,Quentin Tarantino,"John Travolta,Uma Thurman,Samuel L. Jackson"
326,The Lord of the Rings: The Return of the King,17 December 2003,USA,8.9,Peter Jackson,"Elijah Wood,Viggo Mortensen,Ian McKellen"
327,Fight Club,15 October 1999,USA,8.8,David Fincher,"Brad Pitt,Edward Norton,Meat Loaf"

In [19]:
film_rated=new_df.sort_values(by="Film_Rate",ascending=False,ignore_index=True)
film_rated

,Film_Name,Film_Date,Film_Country,Film_Rate,Director,Stars
0,The Shawshank Redemption,14 October 1994,USA,9.3,Frank Darabont,"Tim Robbins,Morgan Freeman,Bob Gunton"
1,The Chaos Class,April 1975,Turkey,9.3,Ertem Egilmez,"Kemal Sunal,Münir Özkul,Halit Akçatepe"
2,The Godfather,24 March 1972,USA,9.2,Francis Ford Coppola,"Marlon Brando,Al Pacino,James Caan"
3,Leyla and Mecnun,TV Series,2011–2014,9.1,Ali Atay,"Ali Atay,Ahmet Mümtaz Taylan,Serkan Keskin"
4,The Godfather: Part II,18 December 1974,USA,9.0,Francis Ford Coppola,"Al Pacino,Robert De Niro,Robert Duvall"
...,...,...,...,...,...,...
323,Bilincsizler,26 December 2015,Turkey,7.4,Furkan Kopuz,"Nuray Guneci,Furkan Kopuz,Metin Cemal Aydin"
324,The Hobbit: The Battle of the Five Armies,17 December 2014,USA,7.4,Peter Jackson,"Ian McKellen,Martin Freeman,Richard Armitage"
325,Insomnia,24 May 2002,USA,7.2,Christopher Nolan,"Al Pacino,Robin Williams,Hilary Swank"
326,Conquest 1453,25 April 2012,USA,6.7,Faruk Aksoy,"Devrim Evin,Ibrahim Celikkol,Dilek Serbest"
327,Sekiz Cinayeti,19 May 2013,Turkey,6.0,Furkan Kopuz,"Furkan Kopuz,Ömer Faruk Kopuz,Ercan Kopuz"